export default {
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    { name: 'name', title: 'Name', type: 'string', validation: (R: any) => R.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name' } },
    { name: 'tagline', title: 'Tagline', type: 'string' },
    { name: 'problem', title: 'The problem', type: 'text', rows: 3, description: 'What needed to exist and why' },
    { name: 'approach', title: 'The approach', type: 'text', rows: 5, description: 'How it works, plainly' },
    { name: 'outcome', title: 'What came of it', type: 'text', rows: 3, description: 'What it produced or proved' },
    { name: 'body', title: 'Body', type: 'text', rows: 10, description: 'Optional longer markdown, rendered below the three sections' },
    { name: 'live_url', title: 'Live URL', type: 'url' },
    { name: 'repo_url', title: 'Repo URL', type: 'url' },
    { name: 'github_sync', title: 'Sync GitHub stars', type: 'boolean', initialValue: false },
    { name: 'featured', title: 'Featured', type: 'boolean', initialValue: true },
    { name: 'status', title: 'Status', type: 'string', options: { list: ['active', 'archived'] }, initialValue: 'active' },
    { name: 'sort', title: 'Sort order', type: 'number', initialValue: 0 },
  ],
  orderings: [{ title: 'Sort order', name: 'sort', by: [{ field: 'sort', direction: 'asc' }] }],
};
